# Prometheus Configuration v2.45.0
# Main configuration file for Medical Research Platform monitoring system

global:
  # Global settings for all scrape targets
  scrape_interval: 15s     # How frequently to scrape targets
  evaluation_interval: 15s # How frequently to evaluate rules
  scrape_timeout: 10s     # Timeout for scrape requests
  
  # External labels to identify this Prometheus instance
  external_labels:
    environment: production
    region: us-east-1

# Rule files containing recording and alerting rules
rule_files:
  - "alerts.yml"  # Alert rules for system, infrastructure, and security monitoring
  - "rules.yml"   # Recording rules for metric aggregation and optimization

# Scrape configurations for monitoring targets
scrape_configs:
  # API Service Monitoring
  - job_name: 'api'
    metrics_path: '/metrics'
    scheme: 'https'
    basic_auth:
      username: '${METRICS_USER}'
      password: '${METRICS_PASSWORD}'
    tls_config:
      cert_file: '/etc/prometheus/certs/client.crt'
      key_file: '/etc/prometheus/certs/client.key'
      ca_file: '/etc/prometheus/certs/ca.crt'
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'api'
          environment: 'production'
          team: 'backend'

  # Node Exporter for System Metrics
  - job_name: 'node'
    metrics_path: '/metrics'
    scheme: 'https'
    basic_auth:
      username: '${METRICS_USER}'
      password: '${METRICS_PASSWORD}'
    tls_config:
      cert_file: '/etc/prometheus/certs/client.crt'
      key_file: '/etc/prometheus/certs/client.key'
      ca_file: '/etc/prometheus/certs/ca.crt'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node'
          environment: 'production'
          team: 'infrastructure'

  # PostgreSQL Database Monitoring
  - job_name: 'database'
    metrics_path: '/metrics'
    scheme: 'https'
    basic_auth:
      username: '${METRICS_USER}'
      password: '${METRICS_PASSWORD}'
    tls_config:
      cert_file: '/etc/prometheus/certs/client.crt'
      key_file: '/etc/prometheus/certs/client.key'
      ca_file: '/etc/prometheus/certs/ca.crt'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'database'
          environment: 'production'
          team: 'infrastructure'

  # Redis Cache Monitoring
  - job_name: 'cache'
    metrics_path: '/metrics'
    scheme: 'https'
    basic_auth:
      username: '${METRICS_USER}'
      password: '${METRICS_PASSWORD}'
    tls_config:
      cert_file: '/etc/prometheus/certs/client.crt'
      key_file: '/etc/prometheus/certs/client.key'
      ca_file: '/etc/prometheus/certs/ca.crt'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'cache'
          environment: 'production'
          team: 'infrastructure'

# Alertmanager configuration
alerting:
  alertmanagers:
    - scheme: 'https'
      basic_auth:
        username: '${ALERTMANAGER_USER}'
        password: '${ALERTMANAGER_PASSWORD}'
      tls_config:
        cert_file: '/etc/prometheus/certs/client.crt'
        key_file: '/etc/prometheus/certs/client.key'
        ca_file: '/etc/prometheus/certs/ca.crt'
      static_configs:
        - targets: ['alertmanager:9093']